Ucb 99
RadoV18/internship-ucb-backend pull request #13
Opened 2023-05-12 03:57 UTC by kevinlm2282

2023-05-14 23:32 UTC, kalatakaya requested changes

2023-05-14 23:32 UTC, kalatakaya commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:intership}
remove your local configurations please

2023-05-15 01:38 UTC, RadoV18 approved these changes

2023-05-15 01:40 UTC, kalatakaya approved these changes

2023-05-17 19:07 UTC, closed without merging