Ucb 9
RadoV18/internship-ucb-backend pull request #17
Opened 2023-05-13 23:12 UTC by ArielMonroy99

2023-05-14 23:17 UTC, RadoV18 requested changes

2023-05-14 23:17 UTC, RadoV18 commented on src/main/java/ucb/internship/backend/mappers/InternshipListMapper.java
> +        internshipList.setCity((String) object[6]);
The API response has the institution name on the city field and vice versa.

2023-05-14 23:26 UTC, kalatakaya commented on src/main/java/ucb/internship/backend/controllers/InternshipController.java
> +            @RequestParam(required = false) Integer size){
You don't need to add all the params like this, you can create a record class that holds this instead

2023-05-14 23:28 UTC, kalatakaya commented on src/main/java/ucb/internship/backend/models/InternshipMajor.java
> +    public boolean isStatus() {
is Status doesn't make clear the intention, should be isActive or whatever you need

2023-05-15 03:03 UTC, RadoV18 approved these changes

2023-05-15 03:03 UTC, merged